name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/screens/images/bu-close.png
    - assets/screens/images/social-icons.png
    - assets/screens/images/vector.png
    - assets/screens/images/bu-close-Pdj.png
    - assets/screens/images/group-6795.png
    - assets/screens/images/auto-group-q27r.png
    - assets/screens/images/icon.png
    - assets/screens/images/vector-e4q.png
    - assets/screens/images/component-4.png
    - assets/screens/images/icons.png
    - assets/screens/images/icon-9FX.png
    - assets/screens/images/icon-hku.png
    - assets/screens/images/icon-gTj.png
    - assets/screens/images/icon-URX.png
    - assets/screens/images/avatar-add-button.png
    - assets/screens/images/icon-jGm.png
    - assets/screens/images/toggle.png
    - assets/screens/images/icon-chevron-arrow-down.png
    - assets/screens/images/icon-Jyo.png
    - assets/screens/images/vector-7xM.png
    - assets/screens/images/avatar-add-button-2am.png
    - assets/screens/images/icon-L8h.png
    - assets/screens/images/icon-RTP.png
    - assets/screens/images/icon-a7K.png
    - assets/screens/images/icon-calendar-date-1.png
    - assets/screens/images/bu-close-NPj.png
    - assets/screens/images/auto-group-korf.png
    - assets/screens/images/auto-group-hzmh.png
    - assets/screens/images/icon-chevron-arrow-right.png
    - assets/screens/images/mask-group.png
    - assets/screens/images/bu-close-oHs.png
    - assets/screens/images/union.png
    - assets/screens/images/avatar-add-button-9Nh.png
    - assets/screens/images/mask-group-Hyj.png
    - assets/screens/images/mask-group-MLd.png
    - assets/screens/images/icon-chevron-arrow-down-EXb.png
    - assets/screens/images/mask-group-mGd.png
    - assets/screens/images/mask-group-9jo.png
    - assets/screens/images/vector-tBb.png
    - assets/screens/images/mask-group-F29.png
    - assets/screens/images/images-1.png
    - assets/screens/images/e74ac8d9ea10baa72c5e4895c4fdfea-1.png
    - assets/screens/images/bu-close-7bX.png
    - assets/screens/images/avatar-add-button-qGd.png
    - assets/screens/images/icons-nSm.png
    - assets/screens/images/a200f3a047d1df379b80710844a9d-1.png
    - assets/screens/images/mask-group-tvD.png
    - assets/screens/images/mask-group-dHK.png
    - assets/screens/images/icons-9Cu.png
    - assets/screens/images/group.png
    - assets/screens/images/c2dd9632df00ec675fdcf6d2fac92-1.png
    - assets/screens/images/mask-group-nj3.png
    - assets/screens/images/mask-group-SwK.png
    - assets/screens/images/icon-K9s.png
    - assets/screens/images/icon-style4.png
    - assets/screens/images/icon-four-square-menu-tile.png
    - assets/screens/images/union-dpm.png
    - assets/screens/images/vector-ytd.png
    - assets/screens/images/union-Dny.png
    - assets/screens/images/portraitelsaleydier-21000x-1.png
    - assets/screens/images/icon-style4-RPF.png
    - assets/screens/images/icon-82m.png
    - assets/screens/images/mask-group-uv1.png
    - assets/screens/images/portraitelsaleydier-21000x-2.png
    - assets/screens/images/c2dd9632df00ec675fdcf6d2fac92-2.png
    - assets/screens/images/mask-group-r8H.png
    - assets/screens/images/mask-group-NAD.png
    - assets/screens/images/mask-group-NFb.png
    - assets/screens/images/fba30ae1da4d257e0207d484b5714d1-1.png
    - assets/screens/images/mask-group-Rvy.png
    - assets/screens/images/e1f3ed36783fb1bddb1480f9c7b15e02-1.png
    - assets/screens/images/auto-group-rg2s.png
    - assets/screens/images/toggle-4TT.png
    - assets/screens/images/icon-D5T.png
    - assets/screens/images/avatar-add-button-Xdb.png
    - assets/screens/images/mask-group-qxV.png
    - assets/screens/images/mask-group-zMX.png
    - assets/screens/images/union-Bqs.png
    - assets/screens/images/icon-921.png
    - assets/screens/images/images-1-iUh.png
    - assets/screens/images/bu-close-4sK.png
    - assets/screens/images/icon-DVK.png
    - assets/screens/images/mask-group-KKP.png
    - assets/screens/images/portraitelsaleydier-21000x-3.png
    - assets/screens/images/e4bc38f2e4a6eb1501eae0de9dd-1.png
    - assets/screens/images/icons-7xV.png
    - assets/screens/images/icon-pencil-edit-1.png
    - assets/screens/images/mask-group-PLm.png
    - assets/screens/images/images-1-4t9.png
    - assets/screens/images/mask-group-4Mf.png
    - assets/screens/images/icon-chevron-arrow-down-vTs.png
    - assets/screens/images/icon-chevron-arrow-down-TTo.png
    - assets/screens/images/portraitelsaleydier-21000x-4.png
    - assets/screens/images/icon-visible.png
    - assets/screens/images/icon-nnd.png
    - assets/screens/images/portraitelsaleydier-21000x-1-FNR.png
    - assets/screens/images/vector-TUV.png
    - assets/screens/images/mask-group-d7P.png
    - assets/screens/images/avatar-add-button-fFP.png
    - assets/screens/images/mask-group-zoT.png
    - assets/screens/images/mask-group-u61.png
    - assets/screens/images/mask-group-n1F.png
    - assets/screens/images/mask-group-XEh.png
    - assets/screens/images/icon-ftM.png
    - assets/screens/images/portraitelsaleydier-21000x-2-ni5.png
    - assets/screens/images/mask-group-KxV.png
    - assets/screens/images/mask-group-iJD.png
    - assets/screens/images/icon-wwP.png
    - assets/screens/images/icon-3zR.png
    - assets/screens/images/icon-yt5.png
    - assets/screens/images/auto-group-gw5m.png
    - assets/screens/images/union-HNy.png
    - assets/screens/images/component-4-DGd.png
    - assets/screens/images/union-YZo.png
    - assets/screens/images/component-4-VV3.png
    - assets/screens/images/icon-ecq.png
    - assets/screens/images/vector-pGR.png
    - assets/screens/images/toggle-aFb.png
    - assets/screens/images/mask-group-mqs.png
    - assets/screens/images/philipp-potocnik-5rsnohd8by8-unsplash-1.png
    - assets/screens/images/menu-bar.png
    - assets/screens/images/mask-group-StH.png
    - assets/screens/images/philipp-potocnik-5rsnohd8by8-unsplash-1-tW5.png
    - assets/screens/images/mask-group-nYR.png
    - assets/screens/images/mask-group-JYR.png
    - assets/screens/images/mask-group-qt5.png
    - assets/screens/images/icon-JhX.png
    - assets/screens/images/mask-group-FP7.png
    - assets/screens/images/mask-group-ndw.png
    - assets/screens/images/mask-group-qNZ.png
    - assets/screens/images/philipp-potocnik-5rsnohd8by8-unsplash-1-BE9.png
    - assets/screens/images/mask-group-Y6m.png
    - assets/screens/images/icons-Np1.png
    - assets/screens/images/mask-group-fKf.png
    - assets/screens/images/icon-s9s.png
    - assets/screens/images/mask-group-uMj.png
    - assets/screens/images/mask-group-UKj.png
    - assets/screens/images/mask-group-F4d.png
    - assets/screens/images/c2dd9632df00ec675fdcf6d2fac92-3.png
    - assets/screens/images/icon-v5X.png
    - assets/screens/images/icon-oD3.png
    - assets/screens/images/bu-close-M7f.png
    - assets/screens/images/mask-group-NU1.png
    - assets/screens/images/mask-group-cEm.png
    - assets/screens/images/mask-group-JNV.png
    - assets/screens/images/mask-group-yxm.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
